blank_issues_enabled: true
contact_links:
  - name: Contact Support
    url: https://support.recaptime.eu.org/contact
    about: Need to contact an squad member for support? Please do not submit support inquiries publicly and use direct communication channels instead.
